language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn ci

deploy:
  provider: npm
  email: accounts@francoisbest.com
  api_key:
    secure: dmTo3iBvdKtcgA5K3dIDgG+uPfkujEiGSkJNCvZUNbsMi//jiPprhbAokpwjZAzqmJH+miOrdYJpEVGFywpfnc6NBxye0818AOTY0U1mWMVaf1IqWk2v6V5zjcRr+CusXlG74HKM8oymcocrQHyQL4z2LA/SpkqvNTmy4oUWuMYUw+InWlk5dTrmoqeMd0EdWCFnUEGlm5RS+YIN0C7UjrJQp8JXwdDzniWm8kcBMC6ml9wmDDPbxOtMhdtFlysTzmGWCsMsq98jh7D+m9W7bU0jW43eylSgiQ8XcZEDR3Ttj7RXMNS3VdVlR7qx062r1y27xwB0zFxe1f3MeWslLoOnyhnWieYoEG6g7iL4JpPNZwKfm/DkVwIAa93anBF1ULNnQPvPml5wgFjXq8COhWmEhFDuljyqLUsGgSODXbcnnRuXqSzLSdzji9ZM47vUqYsYiyus5fxi4pNsrwbqO90pUsGWr06VSR2mPt5LmxkDrbGtXn6+mnNcl/jtvt4av/pd2xXyOOP9BUG66Jpx9zt+xGxQBRO+6rQ7w2nX42y2inU+nTuLHGdm06AAhmqUbo3vmf/GwRL3JQk7qs8oXqQlZoeSJf+WSNRCNMUYsEwatK+LoVGqDGOjsz0dG+pcXxTh7DZkM7qn8LCiSIbqkgBeQlckzaQWc9ESBAlSVd8=
  on:
    tags: true
  skip_cleanup: true

notifications:
  slack:
    rooms:
      secure: PF35e2nU3jiHW4p+Vuy83KwvEp84YjoLq2ndmlu7t/ampZIWQ5HL6zRhUleEYpJ7XU9a9bhsckgfxw/rars/sZhNn7ZjKDT3JKOF57VHdE0rkXUs/aSh+N8+CbYoTdAh1VfA2fxPVHeCxUvOLyjj0JJqY6J3obuq/dq8l+ibQeMQIjvzWTmapCO0yB3I1Ih7F/Iyy+TScNSPL/VmCpiH5iNvcNouCB6jJEuawzzniIl76NZggv+5zYmoMytjuR/OxRMe9I1YN7aZ9kusgLMHqWwgCM0K04pWsy7XwV4w4opTHdhcWBKUT2NjA6DwECESGeysMcU+ZRbLhmE3DcIioCf7A7wl7XRgYerzTtAdRTk4pTLUT2Cy5mcKhGNs3z62sZLaSanXAtEQVA5mw9svTVkwLtl5lACo2paK90Us+fjWvchE8DaiG/ccOwkPo/vggxUI1wP28nTSPCElSBf/ZvZh0Y4tNf1igq87riFtTrYF843LDCOmZeL4QkQoK7oZaVI2xMKiRWQSNkEHbWu/aGojCLf9uMQPdHM5ON4IJ2OHvkq20C8SNadE8EH8MVFmqavzgsdqYbctTmEBrkmgzMEVUuoFN2I3Ru+KcIvwzEp8rxrcc8Nw63mmk8GNmLoQRNm8JxkuPSGcsmARjTyFyeNvUJse4nz8XnLFNUwvo+I=
    on_success: change
    on_failure: always
